name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and run with Docker Compose
        run: |
          docker-compose up --build -d
          sleep 10  # Give containers time to start

      - name: Check backend
        run: |
          curl --fail http://localhost:5000/ || (docker-compose logs backend && exit 1)

      - name: Check frontend
        run: |
          curl --fail http://localhost:5001/ || (docker-compose logs frontend && exit 1)

      - name: Show logs if failed
        if: failure()
        run: docker-compose logs

      - name: Shutdown
        if: always()
        run: docker-compose down
